# lex-ocpp — JSON Schema → lex-schema codegen
#
# Reads an OCPP-style JSON Schema document (single top-level object,
# `properties` + `required` + primitive types + enum constraints)
# and emits a Lex source fragment that defines a matching
# `ModelSchema` value plus a `validate_<action>_req` wrapper.
#
# Scope of v0.1:
#   ✅ top-level `type: object` schemas
#   ✅ primitives: string, integer, number, boolean
#   ✅ `required` array → required vs optional
#   ✅ `enum` arrays on string properties → StrOneOf
#   ✅ string min/maxLength → StrMinLen / StrMaxLen
#   ✅ int minimum/maximum → IntInRange
#   ✅ arrays of primitives → KStr/KInt/KFloat/KBool element kind
#   ✅ arrays of nested objects → emits a nested ModelSchema fn
#
# Deferred (issue against this repo when we hit a use case):
#   ⏭️  $ref resolution across files
#   ⏭️  oneOf / anyOf / allOf
#   ⏭️  pattern (regex) constraints — emit raw StrPattern strings
#   ⏭️  format hints (uri, date-time, uuid) — already covered by
#       lex-schema's StrEmail / StrUrl / StrUuid; wire them in here
#
# Effects: none. Pure Str → Str transformation.
#
# Usage (inside lex-ocpp):
#   lex run tools/gen.lex generate '"<json-schema-string>"'

import "std.str"  as str
import "std.int"  as int
import "std.list" as list

import "lex-schema/json_value" as jv

# ---- Entry point -------------------------------------------------

# Read a JSON Schema string and emit the corresponding Lex source.
# Returns the source on success, or an error message on parse
# failure. Always pure — the caller decides whether to write the
# result to disk.
fn generate(schema_json :: Str) -> Result[Str, Str] {
  match jv.parse(schema_json) {
    Err(p) => Err(str.concat("invalid JSON schema: ", p.message)),
    Ok(j)  => match jv.as_obj(j) {
      None    => Err("schema root must be an object"),
      Some(_) => Ok(emit_top_level(j)),
    },
  }
}

# ---- Emission -----------------------------------------------------

fn emit_top_level(j :: jv.Json) -> Str {
  let title       := field_str_or(j, "title",    "GeneratedSchema")
  let description := field_str_or(j, "description", "")
  let fields_src  := emit_fields(j)
  let model_name  := snake_case(title)
  let model_fn    := str.concat(model_name, "_schema")
  let validator_fn := str.concat("validate_", model_name)
  str.concat(
    header(title),
    str.concat(
      emit_model_schema_fn(model_fn, title, description, fields_src),
      emit_validator_fn(validator_fn, model_fn)))
}

fn header(title :: Str) -> Str {
  str.concat(
    "# Generated by tools/gen.lex from a JSON Schema document.\n",
    str.concat(
      "# Schema title: ", str.concat(title, "\n#\n")))
}

fn emit_model_schema_fn(
  fn_name     :: Str,
  title       :: Str,
  description :: Str,
  fields      :: Str
) -> Str {
  str.concat("fn ", str.concat(fn_name,
    str.concat("() -> s.ModelSchema {\n  {\n    title: \"",
      str.concat(title,
        str.concat("\",\n    description: \"",
          str.concat(description,
            str.concat("\",\n    fields: [\n",
              str.concat(fields, "    ],\n  }\n}\n\n"))))))))
}

fn emit_validator_fn(validator_fn :: Str, schema_fn :: Str) -> Str {
  str.concat("fn ", str.concat(validator_fn,
    str.concat("(j :: jv.Json) -> Result[jv.Json, List[e.Error]] {\n  s.validate(",
      str.concat(schema_fn, "(), j)\n}\n"))))
}

# ---- Field walker ------------------------------------------------

fn emit_fields(j :: jv.Json) -> Str {
  let required_set := required_field_set(j)
  match jv.get_field(j, "properties") {
    None       => "",
    Some(props) => match jv.as_obj(props) {
      None        => "",
      Some(pairs) => list.fold(pairs, "",
        fn (acc :: Str, p :: (Str, jv.Json)) -> Str {
          let name      := match p { (k, _) => k }
          let spec      := match p { (_, v) => v }
          let required  := list_contains(required_set, name)
          str.concat(acc, emit_field(name, spec, required))
        }),
    },
  }
}

fn emit_field(name :: Str, spec :: jv.Json, required :: Bool) -> Str {
  let inner := emit_field_inner(name, spec)
  let line  := if required { inner }
    else { str.concat("s.optional(", str.concat(inner, ")")) }
  str.concat("      ", str.concat(line, ",\n"))
}

fn emit_field_inner(name :: Str, spec :: jv.Json) -> Str {
  let ty := field_str_or(spec, "type", "string")
  match ty {
    "string" => emit_str_field(name, spec),
    "integer" => emit_int_field(name, spec),
    "number"  => emit_float_field(name, spec),
    "boolean" => emit_bool_field(name),
    "array"   => emit_array_field(name, spec),
    "object"  => str.concat("s.required_object(\"",
      str.concat(name,
        str.concat("\", /* nested schema TODO: */ ", "_nested_schema())"))),
    _ => str.concat("s.required_str(\"",
           str.concat(name, "\", [])  /* unknown type, falling back to string */")),
  }
}

# ---- Per-type emitters -------------------------------------------

fn emit_str_field(name :: Str, spec :: jv.Json) -> Str {
  let checks := emit_str_checks(spec)
  str.concat("s.required_str(\"",
    str.concat(name, str.concat("\", ", str.concat(checks, ")"))))
}

fn emit_int_field(name :: Str, spec :: jv.Json) -> Str {
  let checks := emit_int_checks(spec)
  str.concat("s.required_int(\"",
    str.concat(name, str.concat("\", ", str.concat(checks, ")"))))
}

fn emit_float_field(name :: Str, _spec :: jv.Json) -> Str {
  str.concat("s.required_float(\"", str.concat(name, "\", [])"))
}

fn emit_bool_field(name :: Str) -> Str {
  str.concat("s.required_bool(\"", str.concat(name, "\")"))
}

fn emit_array_field(name :: Str, spec :: jv.Json) -> Str {
  let elem_kind := match jv.get_field(spec, "items") {
    None    => "KStr([])",
    Some(items_spec) => match field_str_or(items_spec, "type", "string") {
      "string"  => str.concat("KStr(", str.concat(emit_str_checks(items_spec), ")")),
      "integer" => str.concat("KInt(", str.concat(emit_int_checks(items_spec), ")")),
      "number"  => "KFloat([])",
      "boolean" => "KBool",
      "object"  => "KObject(/* nested ModelSchema TODO */ _nested_schema())",
      _ => "KStr([])",
    },
  }
  let shape_checks := if has_min_items(spec) { "[ListNonEmpty]" } else { "[]" }
  str.concat("s.required_array(\"",
    str.concat(name,
      str.concat("\", ",
        str.concat(elem_kind,
          str.concat(", ", str.concat(shape_checks, ")"))))))
}

# ---- String-constraint emission ---------------------------------

fn emit_str_checks(spec :: jv.Json) -> Str {
  let parts := list.fold(
    list.concat(
      list.concat(
        enum_check(spec),
        min_len_check(spec)),
      max_len_check(spec)),
    "", fn (acc :: Str, p :: Str) -> Str {
      if str.is_empty(acc) { p } else { str.concat(acc, str.concat(", ", p)) }
    })
  str.concat("[", str.concat(parts, "]"))
}

fn enum_check(spec :: jv.Json) -> List[Str] {
  match jv.get_field(spec, "enum") {
    None       => [],
    Some(en_j) => match jv.as_list(en_j) {
      None     => [],
      Some(xs) => {
        let str_values := list.fold(xs, [],
          fn (acc :: List[Str], j :: jv.Json) -> List[Str] {
            match jv.as_str(j) {
              None    => acc,
              Some(s) => list.concat(acc, [str.concat("\"", str.concat(s, "\""))]),
            }
          })
        if list.is_empty(str_values) { [] }
        else {
          [str.concat("StrOneOf([",
             str.concat(str.join(str_values, ", "), "])"))]
        }
      },
    },
  }
}

fn min_len_check(spec :: jv.Json) -> List[Str] {
  match jv.get_field(spec, "minLength") {
    None      => [],
    Some(j)   => match jv.as_int(j) {
      None    => [],
      Some(n) => [str.concat("StrMinLen(", str.concat(int.to_str(n), ")"))],
    },
  }
}

fn max_len_check(spec :: jv.Json) -> List[Str] {
  match jv.get_field(spec, "maxLength") {
    None      => [],
    Some(j)   => match jv.as_int(j) {
      None    => [],
      Some(n) => [str.concat("StrMaxLen(", str.concat(int.to_str(n), ")"))],
    },
  }
}

# ---- Integer-constraint emission --------------------------------

fn emit_int_checks(spec :: jv.Json) -> Str {
  let lo_o := match jv.get_field(spec, "minimum") {
    Some(j) => jv.as_int(j),
    None    => None,
  }
  let hi_o := match jv.get_field(spec, "maximum") {
    Some(j) => jv.as_int(j),
    None    => None,
  }
  match (lo_o, hi_o) {
    (Some(lo), Some(hi)) => str.concat("[IntInRange(",
      str.concat(int.to_str(lo),
        str.concat(", ", str.concat(int.to_str(hi), ")]")))),
    (Some(lo), None) => if lo == 0 { "[IntNonNegative]" }
      else { str.concat("[IntMin(", str.concat(int.to_str(lo), ")]")) },
    (None, Some(hi)) => str.concat("[IntMax(", str.concat(int.to_str(hi), ")]")),
    _ => "[]",
  }
}

# ---- Helpers ----------------------------------------------------

fn field_str_or(j :: jv.Json, key :: Str, default :: Str) -> Str {
  match jv.get_field(j, key) {
    None    => default,
    Some(v) => match jv.as_str(v) { Some(s) => s, None => default },
  }
}

fn required_field_set(j :: jv.Json) -> List[Str] {
  match jv.get_field(j, "required") {
    None       => [],
    Some(req_j) => match jv.as_list(req_j) {
      None     => [],
      Some(xs) => list.fold(xs, [],
        fn (acc :: List[Str], v :: jv.Json) -> List[Str] {
          match jv.as_str(v) {
            None    => acc,
            Some(s) => list.concat(acc, [s]),
          }
        }),
    },
  }
}

fn has_min_items(spec :: jv.Json) -> Bool {
  match jv.get_field(spec, "minItems") {
    None    => false,
    Some(j) => match jv.as_int(j) {
      None    => false,
      Some(n) => n >= 1,
    },
  }
}

fn list_contains(xs :: List[Str], target :: Str) -> Bool {
  list.fold(xs, false,
    fn (acc :: Bool, x :: Str) -> Bool {
      if acc { true } else { x == target }
    })
}

# Lowercase a wire-case title into a snake_case identifier suffix.
# "BootNotificationRequest" → "boot_notification_request".
# Pure folding — no regex needed.
fn snake_case(s :: Str) -> Str {
  let chars := str.split(s, "")
  let out := list.fold(list.enumerate(chars), "",
    fn (acc :: Str, p :: (Int, Str)) -> Str {
      let i := match p { (a, _) => a }
      let c := match p { (_, b) => b }
      let lc := str.to_lower(c)
      if i == 0 { lc }
      else { if is_upper(c) { str.concat(acc, str.concat("_", lc)) }
             else { str.concat(acc, c) } }
    })
  out
}

fn is_upper(c :: Str) -> Bool {
  str.to_upper(c) == c and str.to_lower(c) != c
}

# ---- Demo entry --------------------------------------------------
#
# Hand-written sample input that round-trips through the generator.
# Run with: lex run tools/gen.lex demo
# (no JSON-on-the-command-line needed for the smoke test)

fn demo() -> Str {
  let sample := "{\"title\":\"AuthorizeRequest\","
             + "\"description\":\"OCPP 2.0.1 Authorize\","
             + "\"type\":\"object\","
             + "\"required\":[\"idToken\"],"
             + "\"properties\":{"
             +   "\"idToken\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":36},"
             +   "\"certificate\":{\"type\":\"string\",\"maxLength\":5500}"
             + "}}"
  match generate(sample) {
    Ok(src)  => src,
    Err(msg) => str.concat("ERROR: ", msg),
  }
}
