# lex-ocpp — JSON Schema → lex-schema codegen
#
# Reads an OCPP-style JSON Schema document and emits a Lex source
# fragment that defines a matching `ModelSchema` value plus a
# `validate_<action>_req` wrapper.
#
# Effects: none. Pure Str → Str transformation.

import "std.str"  as str
import "std.int"  as int
import "std.list" as list

import "lex-schema/json_value" as jv

# ---- Entry point -------------------------------------------------

fn generate(schema_json :: Str) -> Result[Str, Str] {
  match jv.parse(schema_json) {
    Err(p) => Err(str.concat("invalid JSON schema: ", p.message)),
    Ok(j)  => match jv.as_obj(j) {
      None    => Err("schema root must be an object"),
      Some(_) => Ok(emit_top_level(j)),
    },
  }
}

# ---- Top-level emission ------------------------------------------

fn emit_top_level(root :: jv.Json) -> Str {
  let title       := field_str_or(root, "title",       "GeneratedSchema")
  let description := field_str_or(root, "description", "")
  let model_name  := snake_case(title)
  let model_fn    := str.concat(model_name, "_schema")
  let validator_fn := str.concat("validate_", model_name)
  let defs_src := emit_all_defs(root)
  let body := match detect_discriminator(root) {
    Some(d) => emit_discriminator_dispatcher(model_name, d),
    None    => emit_model_schema_fn(model_fn, title, description,
                                     emit_fields(root, root)),
  }
  str.concat(header(title), str.concat(defs_src,
    str.concat(body, emit_validator_fn(validator_fn, model_fn))))
}

fn header(title :: Str) -> Str {
  str.concat(
    "# Generated by tools/gen.lex from a JSON Schema document.\n",
    str.concat(
      "# Schema title: ", str.concat(title, "\n#\n\n")))
}

fn emit_model_schema_fn(
  fn_name     :: Str,
  title       :: Str,
  description :: Str,
  fields      :: Str
) -> Str {
  str.concat("fn ", str.concat(fn_name,
    str.concat("() -> s.ModelSchema {\n  {\n    title: \"",
      str.concat(title,
        str.concat("\",\n    description: \"",
          str.concat(description,
            str.concat("\",\n    fields: [\n",
              str.concat(fields, "    ],\n  }\n}\n\n"))))))))}

fn emit_validator_fn(validator_fn :: Str, schema_fn :: Str) -> Str {
  str.concat("fn ", str.concat(validator_fn,
    str.concat("(j :: jv.Json) -> Result[jv.Json, List[e.Error]] {\n  s.validate(",
      str.concat(schema_fn, "(), j)\n}\n"))))
}

# ---- $defs / definitions emission --------------------------------

fn emit_all_defs(root :: jv.Json) -> Str {
  let from_defs        := emit_defs_at(root, "$defs", root)
  let from_definitions := emit_defs_at(root, "definitions", root)
  str.concat(from_defs, from_definitions)
}

fn emit_defs_at(root :: jv.Json, key :: Str, _root2 :: jv.Json) -> Str {
  match jv.get_field(root, key) {
    None       => "",
    Some(defs) => match jv.as_obj(defs) {
      None        => "",
      Some(pairs) => list.fold(pairs, "",
        fn (acc :: Str, p :: (Str, jv.Json)) -> Str {
          let name      := match p { (k, _) => k }
          let spec      := match p { (_, v) => v }
          str.concat(acc, emit_one_def(name, spec, root))
        }),
    },
  }
}

fn emit_one_def(name :: Str, spec :: jv.Json, root :: jv.Json) -> Str {
  emit_model_schema_fn(
    str.concat(snake_case(name), "_schema"),
    name,
    field_str_or(spec, "description", ""),
    emit_fields(spec, root))
}

# ---- Discriminated union (oneOf) detection ----------------------

type Discriminator = {
  tag      :: Str,
  branches :: List[(Str, jv.Json)],
}

fn detect_discriminator(root :: jv.Json) -> Option[Discriminator] {
  match jv.get_field(root, "oneOf") {
    None        => None,
    Some(arr_j) => match jv.as_list(arr_j) {
      None        => None,
      Some(arms) =>
        if list.is_empty(arms) { None }
        else {
          match find_first_const_tag(arms) {
            None      => None,
            Some(tag) => match collect_branches(tag, arms) {
              None         => None,
              Some(pairs)  => Some({ tag: tag, branches: pairs }),
            },
          }
        },
    },
  }
}

fn find_first_const_tag(arms :: List[jv.Json]) -> Option[Str] {
  match list.head(arms) {
    None       => None,
    Some(arm)  => first_const_prop(arm),
  }
}

fn first_const_prop(arm :: jv.Json) -> Option[Str] {
  match jv.get_field(arm, "properties") {
    None        => None,
    Some(props) => match jv.as_obj(props) {
      None        => None,
      Some(pairs) => list.fold(pairs, None,
        fn (acc :: Option[Str], p :: (Str, jv.Json)) -> Option[Str] {
          match acc {
            Some(_) => acc,
            None    => {
              let name := match p { (k, _) => k }
              let spec := match p { (_, v) => v }
              match jv.get_field(spec, "const") {
                None    => None,
                Some(_) => Some(name),
              }
            },
          }
        }),
    },
  }
}

fn collect_branches(tag :: Str, arms :: List[jv.Json]) -> Option[List[(Str, jv.Json)]] {
  list.fold(arms, Some([]),
    fn (acc :: Option[List[(Str, jv.Json)]], arm :: jv.Json) -> Option[List[(Str, jv.Json)]] {
      match acc {
        None       => None,
        Some(xs)   => match const_value_for(arm, tag) {
          None      => None,
          Some(val) => Some(list.concat(xs, [(val, arm)])),
        },
      }
    })
}

fn const_value_for(arm :: jv.Json, tag :: Str) -> Option[Str] {
  match jv.get_field(arm, "properties") {
    None        => None,
    Some(props) => match jv.get_field(props, tag) {
      None        => None,
      Some(spec)  => match jv.get_field(spec, "const") {
        None    => None,
        Some(v) => jv.as_str(v),
      },
    },
  }
}

fn emit_discriminator_dispatcher(
  model_name :: Str,
  d          :: Discriminator
) -> Str {
  let branches_src := list.fold(d.branches, "",
    fn (acc :: Str, pair :: (Str, jv.Json)) -> Str {
      let val  := match pair { (v, _) => v }
      let arm  := match pair { (_, a) => a }
      let arm_name := str.concat(model_name, str.concat("_", snake_case(val)))
      let body :=
        emit_model_schema_fn(
          str.concat(arm_name, "_schema"),
          val,
          "",
          emit_fields(arm, arm))
      str.concat(acc, body)
    })
  let table_entries := list.fold(d.branches, "",
    fn (acc :: Str, pair :: (Str, jv.Json)) -> Str {
      let val := match pair { (v, _) => v }
      let arm_name := str.concat(model_name, str.concat("_", snake_case(val)))
      let entry := str.concat("    (\"", str.concat(val,
                      str.concat("\", fn (j :: jv.Json) -> Result[jv.Json, List[e.Error]] { s.validate(",
                        str.concat(arm_name, "_schema(), j) }),\n"))))
      str.concat(acc, entry)
    })
  let dispatcher :=
    str.concat("fn ", str.concat(model_name, str.concat("_schema_dispatch(j :: jv.Json) -> Result[jv.Json, List[e.Error]] {\n",
      str.concat("  union.discriminate(\"\", j, \"", str.concat(d.tag,
        str.concat("\", [\n", str.concat(table_entries, "  ])\n}\n\n")))))))
  str.concat(branches_src, dispatcher)
}

# ---- Field walker ------------------------------------------------

fn emit_fields(spec :: jv.Json, root :: jv.Json) -> Str {
  let required_set := required_field_set(spec)
  match jv.get_field(spec, "properties") {
    None       => "",
    Some(props) => match jv.as_obj(props) {
      None        => "",
      Some(pairs) => list.fold(pairs, "",
        fn (acc :: Str, p :: (Str, jv.Json)) -> Str {
          let name      := match p { (k, _) => k }
          let inner     := match p { (_, v) => v }
          let required  := list_contains(required_set, name)
          str.concat(acc, emit_field(name, inner, required, root))
        }),
    },
  }
}

fn emit_field(
  name     :: Str,
  spec     :: jv.Json,
  required :: Bool,
  root     :: jv.Json
) -> Str {
  let inner := emit_field_inner(name, spec, root)
  let line  := if required { inner }
    else { str.concat("s.optional(", str.concat(inner, ")")) }
  str.concat("      ", str.concat(line, ",\n"))
}

fn emit_field_inner(name :: Str, spec :: jv.Json, root :: jv.Json) -> Str {
  match resolve_ref(spec, root) {
    Some(ref_name) => str.concat("s.required_object(\"",
      str.concat(name,
        str.concat("\", ",
          str.concat(snake_case(ref_name), "_schema())"))))
    None => {
      let ty := field_str_or(spec, "type", "string")
      match ty {
        "string"  => emit_str_field(name, spec),
        "integer" => emit_int_field(name, spec),
        "number"  => emit_float_field(name, spec),
        "boolean" => emit_bool_field(name),
        "array"   => emit_array_field(name, spec, root),
        "object"  => str.concat("s.required_object(\"",
          str.concat(name,
            str.concat("\", /* inline nested object — promote to $defs */ ",
              "_nested_schema())"))),
        _ => str.concat("s.required_str(\"",
               str.concat(name, "\", [])"))
      }
    },
  }
}

# ---- Per-type emitters -------------------------------------------

fn emit_str_field(name :: Str, spec :: jv.Json) -> Str {
  let checks := emit_str_checks(spec)
  str.concat("s.required_str(\"",
    str.concat(name, str.concat("\", ", str.concat(checks, ")"))))
}

fn emit_int_field(name :: Str, spec :: jv.Json) -> Str {
  let checks := emit_int_checks(spec)
  str.concat("s.required_int(\"",
    str.concat(name, str.concat("\", ", str.concat(checks, ")"))))
}

fn emit_float_field(name :: Str, _spec :: jv.Json) -> Str {
  str.concat("s.required_float(\"", str.concat(name, "\", []))")}

fn emit_bool_field(name :: Str) -> Str {
  str.concat("s.required_bool(\"", str.concat(name, "\")"))
}

fn emit_array_field(name :: Str, spec :: jv.Json, root :: jv.Json) -> Str {
  let elem_kind := match jv.get_field(spec, "items") {
    None              => "KStr([])",
    Some(items_spec)  => match resolve_ref(items_spec, root) {
      Some(ref_name) => str.concat("KObject(",
        str.concat(snake_case(ref_name), "_schema())"))
      None => match field_str_or(items_spec, "type", "string") {
        "string"  => str.concat("KStr(", str.concat(emit_str_checks(items_spec), ")")),
        "integer" => str.concat("KInt(", str.concat(emit_int_checks(items_spec), ")")),
        "number"  => "KFloat([])",
        "boolean" => "KBool",
        "object"  => "KObject(/* inline nested object — promote to $defs */ _nested_schema())",
        _ => "KStr([])",
      },
    },
  }
  let shape_checks := if has_min_items(spec) { "[ListNonEmpty]" } else { "[]" }
  str.concat("s.required_array(\"",
    str.concat(name,
      str.concat("\", ",
        str.concat(elem_kind,
          str.concat(", ", str.concat(shape_checks, ")")))))
}

# ---- $ref resolution ---------------------------------------------

fn resolve_ref(spec :: jv.Json, _root :: jv.Json) -> Option[Str] {
  match jv.get_field(spec, "$ref") {
    None       => None,
    Some(ref_j) => match jv.as_str(ref_j) {
      None        => None,
      Some(path)  => extract_ref_name(path),
    },
  }
}

fn extract_ref_name(path :: Str) -> Option[Str] {
  let parts := str.split(path, "/")
  let last := list.fold(parts, "",
    fn (acc :: Str, seg :: Str) -> Str { seg })
  if str.is_empty(last) { None } else { Some(last) }
}

# ---- String-constraint emission ---------------------------------

fn emit_str_checks(spec :: jv.Json) -> Str {
  let parts := list.fold(
    list.concat(
      list.concat(
        list.concat(
          list.concat(
            enum_check(spec),
            min_len_check(spec)),
          max_len_check(spec)),
        pattern_check(spec)),
      format_check(spec)),
    "", fn (acc :: Str, p :: Str) -> Str {
      if str.is_empty(acc) { p } else { str.concat(acc, str.concat(", ", p)) }
    })
  str.concat("[", str.concat(parts, "]"))
}

fn enum_check(spec :: jv.Json) -> List[Str] {
  match jv.get_field(spec, "enum") {
    None       => [],
    Some(en_j) => match jv.as_list(en_j) {
      None     => [],
      Some(xs) => {
        let str_values := list.fold(xs, [],
          fn (acc :: List[Str], j :: jv.Json) -> List[Str] {
            match jv.as_str(j) {
              None    => acc,
              Some(s) => list.concat(acc, [str.concat("\"", str.concat(s, "\""))]),
            }
          })
        if list.is_empty(str_values) { [] }
        else {
          [str.concat("StrOneOf([",
             str.concat(str.join(str_values, ", "), "])"))]
        }
      },
    },
  }
}

fn min_len_check(spec :: jv.Json) -> List[Str] {
  match jv.get_field(spec, "minLength") {
    None      => [],
    Some(j)   => match jv.as_int(j) {
      None    => [],
      Some(n) => [str.concat("StrMinLen(", str.concat(int.to_str(n), ")"))],
    },
  }
}

fn max_len_check(spec :: jv.Json) -> List[Str] {
  match jv.get_field(spec, "maxLength") {
    None      => [],
    Some(j)   => match jv.as_int(j) {
      None    => [],
      Some(n) => [str.concat("StrMaxLen(", str.concat(int.to_str(n), ")"))],
    },
  }
}

fn pattern_check(spec :: jv.Json) -> List[Str] {
  match jv.get_field(spec, "pattern") {
    None      => [],
    Some(j)   => match jv.as_str(j) {
      None    => [],
      Some(p) => [str.concat("StrPattern(\"",
                    str.concat(escape_str_literal(p), "\""))],
    },
  }
}

fn format_check(spec :: jv.Json) -> List[Str] {
  match jv.get_field(spec, "format") {
    None      => [],
    Some(j)   => match jv.as_str(j) {
      None    => [],
      Some(f) => match map_format(f) {
        Some(constraint) => [constraint],
        None             => [],
      },
    },
  }
}

fn map_format(f :: Str) -> Option[Str] {
  match f {
    "uri"       => Some("StrUrl"),
    "uri-reference" => Some("StrUrl"),
    "url"       => Some("StrUrl"),
    "email"     => Some("StrEmail"),
    "uuid"      => Some("StrUuid"),
    "date-time" => Some("StrNonEmpty /* date-time: validate downstream via lex-schema/datetime */"),
    "date"      => Some("StrIsoDate"),
    "time"      => Some("StrIsoTime"),
    "ipv4"      => Some("StrIPv4"),
    "ipv6"      => Some("StrIPv6"),
    "hostname"  => Some("StrHostname"),
    _           => None,
  }
}

# ---- Integer-constraint emission --------------------------------

fn emit_int_checks(spec :: jv.Json) -> Str {
  let lo_o := match jv.get_field(spec, "minimum") {
    Some(j) => jv.as_int(j),
    None    => None,
  }
  let hi_o := match jv.get_field(spec, "maximum") {
    Some(j) => jv.as_int(j),
    None    => None,
  }
  match (lo_o, hi_o) {
    (Some(lo), Some(hi)) => str.concat("[IntInRange(",
      str.concat(int.to_str(lo),
        str.concat(", ", str.concat(int.to_str(hi), ")]")))),
    (Some(lo), None) => if lo == 0 { "[IntNonNegative]" }
      else { str.concat("[IntMin(", str.concat(int.to_str(lo), ")]")) },
    (None, Some(hi)) => str.concat("[IntMax(", str.concat(int.to_str(hi), ")]")) ,
    _ => "[]",
  }
}

# ---- Helpers -----------------------------------------------------

fn field_str_or(j :: jv.Json, key :: Str, default :: Str) -> Str {
  match jv.get_field(j, key) {
    None    => default,
    Some(v) => match jv.as_str(v) { Some(s) => s, None => default },
  }
}

fn required_field_set(j :: jv.Json) -> List[Str] {
  match jv.get_field(j, "required") {
    None       => [],
    Some(req_j) => match jv.as_list(req_j) {
      None     => [],
      Some(xs) => list.fold(xs, [],
        fn (acc :: List[Str], v :: jv.Json) -> List[Str] {
          match jv.as_str(v) {
            None    => acc,
            Some(s) => list.concat(acc, [s]),
          }
        }),
    },
  }
}

fn has_min_items(spec :: jv.Json) -> Bool {
  match jv.get_field(spec, "minItems") {
    None    => false,
    Some(j) => match jv.as_int(j) {
      None    => false,
      Some(n) => n >= 1,
    },
  }
}

fn list_contains(xs :: List[Str], target :: Str) -> Bool {
  list.fold(xs, false,
    fn (acc :: Bool, x :: Str) -> Bool {
      if acc { true } else { x == target }
    })
}

fn escape_str_literal(s :: Str) -> Str {
  let chars := str.split(s, "")
  list.fold(chars, "",
    fn (acc :: Str, c :: Str) -> Str {
      let escaped := match c {
        "\"" => "\\\"",
        "\\" => "\\\\",
        _    => c,
      }
      str.concat(acc, escaped)
    })
}

fn snake_case(s :: Str) -> Str {
  let chars := str.split(s, "")
  list.fold(list.enumerate(chars), "",
    fn (acc :: Str, p :: (Int, Str)) -> Str {
      let i := match p { (a, _) => a }
      let c := match p { (_, b) => b }
      let lc := str.to_lower(c)
      if i == 0 { lc }
      else { if is_upper(c) { str.concat(acc, str.concat("_", lc)) }
             else { str.concat(acc, c) } }
    })
}

fn is_upper(c :: Str) -> Bool {
  str.to_upper(c) == c and str.to_lower(c) != c
}

# ---- Demo entry --------------------------------------------------

fn demo() -> Str {
  let id_token_props :=
    str.concat("\"idToken\":{\"type\":\"string\",\"maxLength\":36},",
      "\"type\":{\"type\":\"string\",\"enum\":[\"Central\",\"ISO14443\"]}")
  let id_token_def :=
    str.concat("{\"type\":\"object\",\"required\":[\"idToken\",\"type\"],\"properties\":{",
      str.concat(id_token_props, "}}"))
  let defs_block :=
    str.concat("\"$defs\":{\"IdToken\":", str.concat(id_token_def, "},"))
  let root_props :=
    str.concat("\"idToken\":{\"$ref\":\"#/$defs/IdToken\"},",
      "\"certificate\":{\"type\":\"string\",\"maxLength\":5500,\"format\":\"uri\"}")
  let sample :=
    str.concat("{\"title\":\"AuthorizeRequest\",",
      str.concat("\"description\":\"OCPP 2.0.1 Authorize\",",
        str.concat("\"type\":\"object\",",
          str.concat(defs_block,
            str.concat("\"required\":[\"idToken\"],",
              str.concat("\"properties\":{",
                str.concat(root_props, "}}")))))))  
  match generate(sample) {
    Ok(src)  => src,
    Err(e)   => str.concat("ERROR: ", e),
  }
}
